name: urlzap
on: [push]
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Generate & Deploy
    steps:
    # Checkout your repo locally
    - uses: actions/checkout@v2

    # Build config from csv
    - name: Build
      shell: bash
      run: |
        sudo snap install yq
        sudo apt-get install -y csvkit
        csvjson links.csv --no-header-row | jq '{ path: "out", urls: map({(.a + "/" + (.b | tostring)): .c}) | add }' | yq -P > config.yml
        
    # Generate files using this action
    - name: Generate
      uses: brunoluiz/urlzap-github-action@v1

    # Deplloy in Github Pages (you can use others)
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out