name: urlzap
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Generate & Deploy
    steps:
    # Checkout your repo locally
    - uses: actions/checkout@v2

    - name: Install packages
      run: sudo apt-get install -y jq csvkit
    
    # Build config from csv
    - name: Build
      uses: mikefarah/yq@v4.43.1
      with:
        cmd: |
          csvjson links.csv --no-header-row | jq '{ path: "out", urls: map({(.a | tostring): .b}) | add }' | yq -P > config.yml

    # Generate files using this action
    - name: Generate
      uses: brunoluiz/urlzap-github-action@v1

    # Deplloy in Github Pages (you can use others)
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: out